### ISSUE TITLE
名称相同的联系人无法同时link

### ISSUE THREAD

**Issue by NWindy5** [blueset/ehForwarderBot#102]
使用/link命令之后会出现两个名称相同的选项，但是点哪一个都会提示已经link了（只有relink选项）
微信网页版是可以看出两个联系人的区别的

**Comment by blueset** [comment]
目前受到技术限制，EWS 无法处理重名会话以及没有名称的会话的情况，详情请参见相关文档。

**Comment by blueset** [comment]
This issue was moved to blueset/efb-wechat-slave#2
