### ISSUE TITLE
Doesn't delete original file after converting to GIF

### ISSUE THREAD

**Issue by xiadong1994** [blueset/ehForwarderBot#105]
When I send a saved GIF from Telegram, the filename extension is `.mp4`. The EFB will convert it to `.gif` and send to WeChat. After sending to WeChat, the `.gif` file will be deleted but the original `.mp4` file is remained. I think the file should be deleted after converting in `_download_gif` function in `plugins/eh_telegram_master/__init__.py`.

**Comment by blueset** [comment]
Thanks for the report, I will further investigate on this issue.

**Comment by blueset** [comment]
Media file processing is now handled by Python's Named Temporary File in all my v2 channels, and this should be fixed by now, but untested with EWS due to personal issue.

**Comment by blueset** [comment]
This issue was moved to blueset/efb-telegram-master#5
