### ISSUE TITLE
是无法启动

### ISSUE THREAD

**Issue by ddqp** [blueset/ehForwarderBot#107]
一直运行好好的，今天突然发现telegram无法联通微信了，所以重启了一下服务器上的daemon，可是是无法正常启动最后一行  Initializing master ('plugins.eh_telegram_master', 'TelegramChannel')...之后就没有任何信息了，一直卡在那里，telegram也没反应，

28-12-2017:06:04:28,835 CRITICAL [eh_wechat_slave.py:148]
     **Successfully authorized**.
28-12-2017:06:04:31,117 CRITICAL [main.py:86]
      Slave channel WeChat Slave (eh_wechat_slave) initialized.
28-12-2017:06:04:31,117 CRITICAL [main.py:87]
      Initializing master ('plugins.eh_telegram_master', 'TelegramChannel')...

**Comment by blueset** [comment]
请提供启动时的 Verbose log。
```
python3 main.py -vvv
```

**Comment by ddqp** [comment]
28-12-2017:06:36:09,486 CRITICAL [eh_wechat_slave.py:145]
     Tap "Confirm" to continue.
28-12-2017:06:36:09,554 CRITICAL [eh_wechat_slave.py:145]
     Tap "Confirm" to continue.
28-12-2017:06:36:09,810 CRITICAL [eh_wechat_slave.py:148]
     Successfully authorized.
28-12-2017:06:36:09,810 INFO     [login.py:70]
     Loading the contact, this may take a little while.
28-12-2017:06:36:12,78 INFO     [login.py:80]
     Login successfully as YAN Chao
28-12-2017:06:36:12,110 DEBUG    [hotreload.py:33]
     Dump login status for hot reload successfully.
28-12-2017:06:36:12,112 INFO     [eh_wechat_slave.py:135]
     EWS Inited!!!
---
28-12-2017:06:36:12,113 CRITICAL [main.py:86]
      Slave channel WeChat Slave (eh_wechat_slave) initialized.
28-12-2017:06:36:12,113 CRITICAL [main.py:87]
      Initializing master ('plugins.eh_telegram_master', 'TelegramChannel')...
28-12-2017:06:36:12,962 DEBUG    [contact.py:261]
     No uins in 51 message
28-12-2017:06:36:12,962 DEBUG    [contact.py:262]

28-12-2017:06:36:13,143 DEBUG    [peewee.py:3826]
     ('SELECT name FROM sqlite_master WHERE type = ? ORDER BY name;', ('table',))
28-12-2017:06:36:13,145 DEBUG    [peewee.py:3826]
     ('PRAGMA table_info("msglog")', None)
28-12-2017:06:36:13,146 DEBUG    [peewee.py:3826]
     ('SELECT name FROM sqlite_master WHERE type = ? ORDER BY name;', ('table',))
Illegal instruction

**Comment by blueset** [comment]
`tgdata.db` SQLite 数据库损坏，请在可能的情况下尝试备份其中的数据，并移除该文件重试。

_\* `tgdata.db` 包含了 ETM 的会话绑定以及过去消息记录等内容。移除后需要重新绑定会话。_

**Comment by ddqp** [comment]
说实话，我已经移除了，可是仍然没有变化。输出还是上面那些

**Comment by ddqp** [comment]
还有什么能删掉或者重来的吗

**Comment by ddqp** [comment]
删的文件时这里，对吧：rm plugins/eh_telegram_master/tgdata.db

**Comment by blueset** [comment]
尝试备份并移除所有 EFB 相关文件并重新部署？

**Comment by ddmbr** [comment]
我解决了这个问题，不过原因不一定不一样。在我这边，这是openblas引起的，pip安装的numpy所提供的openblas动态链接库内不一定提供相应平台的指令 (所以会出现illegal instruction的问题)。具体是哪个东西使用了numpy我记不得了，中间有很多层。

所以我估计和这个repo没关系，应该可以关这个issue了。
