### ISSUE TITLE
link到一个群组后，希望添加直接回复功能

### ISSUE THREAD

**Issue by thedogb** [blueset/ehForwarderBot#110]
我现在将一个微信会话link到一个tg群组，这个群组中只有我和这个微信会话。
在这种情况下我依然要选中reply某个消息，才能发到微信会话中，感觉很麻烦。
希望能添加：
>在这种情况下，在群组中发言即发送到微信会话

的功能，这样相当于将一个群组直接映射到了一个微信会话。

**Comment by blueset** [comment]
该功能是有的。

请在绑定的群组内发送 `/info` 确认该群是否仅绑定了一个会话。

**Comment by thedogb** [comment]
哦哦，好的，谢谢。在帮助里每看到这个，以为没有

**Comment by blueset** [comment]
这个是在帮助里面写丢了， 后续 Major 版本会补上的。

**Comment by thedogb** [comment]
额，我在群里发了/info，只是确认了仅绑定了一个会话，但没有其他变化。直接回复依然无效

**Comment by blueset** [comment]
方便发一下重现过程 verbose log 吗？

**Comment by thedogb** [comment]
没有任何log，启动的时候已经加了-vv了，还是没有任何log

**Comment by blueset** [comment]
o_O 不应该呃…… 

verbose 的话只要启动就有 log 出来呃……

**Comment by thedogb** [comment]
```bash
python daemon.py start -vv
```
这是我的启动命令，有问题吗。输出是有，不过是上一次启动留下的log，新的操作没有产生新的log

**Comment by blueset** [comment]
忽然想起来，确认一下有没有找 botfather 关掉 bot 的隐私设定？

是用这个

```
python deamon.py restart -vv
```

**Comment by thedogb** [comment]
ok了，是隐私设定的问题
