### ISSUE TITLE
使用语音识别功能报错

### ISSUE THREAD

**Issue by Besson1412** [blueset/ehForwarderBot#111]
已经在配置文件中添加了申请的api key  等相关信息，但是仍然提示 ：

Baidu (Mandarin):
Not enabled or error in configuration.

Bing (Mandarin):
ERROR!

请问还需要在哪里配置么？

**Comment by blueset** [comment]
Bing 更换了语音识别接口，将在 ETM v2 中修复此问题。

**Comment by blueset** [comment]
已尝试在 ETM v2 修复

**Comment by blueset** [comment]
This issue was moved to blueset/efb-telegram-master#8
