### ISSUE TITLE
I want to translate the project to Nigeria(Yoruba) can i go on pull my request?

### ISSUE THREAD

**Issue by fashionistass** [blueset/ehForwarderBot#118]

**Comment by blueset** [comment]
Hi fashionistass, thanks for your interests. 

EFB currently uses [Crowdin](https://crowdin.com/project/ehforwarderbot) to manage translations, and it will be merged automatically when a new version is published to PyPI.

**Comment by fashionistass** [comment]
Should I wait till the new version will be published , cause No thread for the language (Yoruba Nigeria) on crowd in...
Or how can I go on with that now?
