### ISSUE TITLE
Parsing link to markdown when send from Telegram to Wechat

### ISSUE THREAD

**Issue by nicholascw** [blueset/ehForwarderBot#119]
Using the pip3-installed new 2.0 version, encountering the issue that when sending pure text of link, e.g. `http://example.com` , the Telegram would auto recognize then turn it into a clickable link in Telegram, then it would shown in WeChat like a Markdown-style source code like `[http://example.com](example.com)`. Not knowing if it should be fixed on Telegram Master or the WeChat Slave, so putted here.

**Comment by blueset** [comment]
This issue should go to relative channel's repository.

**Comment by blueset** [comment]
This issue should go to ETM's repository.
