### ISSUE TITLE
收到：服务器的网络环境可能较差...信息

### ISSUE THREAD

**Issue by leedming** [blueset/ehForwarderBot#125]

**Comment by leedming** [comment]
能正常使用，但是就是一天能有20条左右
不断的收到：EFB Telegram 主端
您服务器的网络环境可能较差，目前已检测到 2000 个网络问题。
如需更多信息，请查看日志。
这类信息
请问，怎么样能不提示这样的错误？

**Comment by cainiao2223** [comment]
what？

发自我的 iPhone

**Comment by leedming** [comment]
ehForwarderBot 在telegram上不断收到：“EFB Telegram主端
您的服务器的网络环境可能较差，目前已检测到2000个网络问题。
如需更多信息，请查看日志。”
<img width="348" alt="sp180505_124237" src="https://user-images.githubusercontent.com/11971916/39659737-d7e976a4-5061-11e8-8ff2-53c02a33941a.png">

这信息类

**Comment by blueset** [comment]
This issue was moved to blueset/efb-telegram-master#17
