### ISSUE TITLE
Installation/Management/Control Scripts

### ISSUE THREAD

**Issue by Riajyuu** [blueset/ehForwarderBot#126]
I'm clear this is a bit controversial but maybe adapt it into several popular distros like Ubuntu, Debian, Fedora, etc.?

**Comment by cainiao2223** [comment]
who are you

发自我的 iPhone

**Comment by blueset** [comment]
Thanks for the suggestion.

We will consider this when we release stable version for modules I maintain.

**Comment by blueset** [comment]
As of now, EFB v2 has a wizard program to guide users to setup the environment and check for binary dependencies. Since the framework itself does not depend on any binaries other than Python itself,  anything to do with non-Python dependencies would be better dealt by modules separately.
