### ISSUE TITLE
about other bot automatic forwarding

### ISSUE THREAD

**Issue by w0330t** [blueset/ehForwarderBot#128]
I create a new bot for send  messages regularly
but efbbot not work for the bot
it only work for my account
I need advice
Thanks

**Comment by blueset** [comment]
Please describe your issue in detail. Most likely you are having issue with one of the channels but not EFB framework itself. I suggest you to raise the issue in the repo of the related channel if so. 

Thanks.

**Comment by blueset** [comment]
Closing this issue due to months of inactivity.

**Comment by zhigang1992** [comment]
I think what @w0330t was describing is that 

To be able to send a message to WeChat from another bot, like GitHub integration.

Currently, only the admin's message gets forwarded to chat. And not other bot's message, even though that bot is in the group.

@blueset
