### ISSUE TITLE
Consider using AGPL?

### ISSUE THREAD

**Issue by tleydxdy** [blueset/ehForwarderBot#145]
Hi, 
I was looking in to this cool software and trying to add matrix bridge to it, and I noticed this uses GPLv3. So I would like to suggest AGPL in place of GPL; since this is a server software that people may use via a server, AGPL may be more suitable for it than plain GPL. 

AGPL is just like normal GPL but added rules to protects users' freedom from ASP loophole which let's "Application service provider"s get away from GPL's rules; it's also compatible with normal GPL. 

More on [Why the Affero GPL](https://www.gnu.org/licenses/why-affero-gpl.html)
https://www.gnu.org/licenses/agpl-3.0.en.html

Thank you!

**Comment by blueset** [comment]
Thanks for the suggestion. You've made a good point. I'll release the upcoming versions of EFB and modules maintained by me with AGPL.

**Comment by tleydxdy** [comment]
Awesome!
