### ISSUE TITLE
AttributeError: module 'ehforwarderbot.coordinator' has no attribute 'master'

### ISSUE THREAD

**Issue by ShiinaOrez** [blueset/ehForwarderBot#157]
My OS is Ubuntu18.04, and I want run ehforwarderbot for Tg and CoolQ, all works are done, but when I want to start ehforwarderbot service. (```bash$: ehforwarderbot```) I have this follow log:

```AttributeError: module 'ehforwarderbot.coordinator' has no attribute 'master'```

I repeat install and uninstall by pip3, but it doesn't work.

My whoel error stack:

Traceback (most recent call last):
  File "/home/song-ruyang/.local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 55, in stop_gracefully
    if isinstance(coordinator.master, EFBChannel):
AttributeError: module 'ehforwarderbot.coordinator' has no attribute 'master'

**Comment by blueset** [comment]
Please provide the traceback before this error raised.

**Comment by ShiinaOrez** [comment]
It's  seem like problem on proxy...
