### ISSUE TITLE
AUR packages are available for arch-based system.

### ISSUE THREAD

**Issue by specter119** [blueset/ehForwarderBot#165]
I have created 6 AUR packages (3 for efbs and 3 for efb-deps) for efb related python modules. They worked on my machine with archlinux.

here are aur packages links for efb modules.

<https://aur.archlinux.org/packages/python-ehforwarderbot-git>
<https://aur.archlinux.org/packages/python-efb-wechat-slave-git>
<https://aur.archlinux.org/packages/python-efb-telegram-master-git>

you may activate the systemd unit by `sudo systemctl start ehforwarderbot@<your user name> `.
if it work well, and you can run `sudo systemctl enable ehforwarderbot@<your user name>`  to make it auto-start.

**Comment by blueset** [comment]
Thank you for the contribution. I will include them in their respective documentations.

**Comment by specter119** [comment]
@blueset  Thanks.
