### ISSUE TITLE
An mistake in the document.

### ISSUE THREAD

**Issue by catbaron0** [blueset/ehForwarderBot#168]
In the document for [EFBMsg.edit_media](https://ehforwarderbot.readthedocs.io/zh_CN/latest/API/message.html#ehforwarderbot.EFBMsg.edit_media), it says:

> Flag this up if any file attached to the message is modified. If this value is true, **edit_media** must also be true.

which should be 

> Flag this up if any file attached to the message is modified. If this value is true, **edit** must also be true.

**Comment by blueset** [comment]
Fixed.
