### ISSUE TITLE
Lift "muted" attribute to EFBChat object

### ISSUE THREAD

**Issue by blueset** [blueset/ehForwarderBot#170]
"Muting", or per-chat notification control is a common attribute of chats in multiple IM platforms including WeChat, Facebook Messenger, QQ (partially?), Skype, Slack, Discord, etc.

An attribute like `.notification` can be added to `EFBChat` object with values such as `All`, `Mentions`, and `None`.

**Comment by catbaron0** [comment]
Sounds good.
But I think WeChat doesn't support this feature, so shall we control this notification state from Telegram?

**Comment by blueset** [comment]
This issue is for the EFB framework design, and this `muted` attribute here is inteded to represent whether a chat is "muted" in its slave channel/IM. It doesn't necessarily imply anything in master channels.

**Comment by blueset** [comment]
Released.
