### ISSUE TITLE
Failed to obtain friend remark name

### ISSUE THREAD

**Issue by kevinzhang1234** [blueset/ehForwarderBot#172]
🐧💻 CoolQ Alert:
Failed to obtain friend remark name

不能显示qq昵称，该如何解决

**Comment by blueset** [comment]
This is an issue regarding [efb-qq-slave](https://github.com/milkice233/efb-qq-slave). Please transfer your issue to `efb-qq-slave` repository for an answer. 

This issue is locked due to irrelevance.
