### ISSUE TITLE
[FR] about SIGTERM

### ISSUE THREAD

**Issue by trysh** [blueset/ehForwarderBot#175]
**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**  

sorry about i'm not good at english
about SIGTERM
The efb program has a catch on SIGINT (that is, ctrl+c). In other words, the user presses ctrl+c or sends SIGINT to efb. After waiting a few seconds, it can successfully "quit completely". This is no problem.

but!
Efb" does not "capture SIGTERM. In other words, with kill or pkill, without specifying the signal (using SIGTERM by default), efb is indifferent, causing the waiting time beyond my setting, so I can only use strong kill, so I lose data.

It is recommended that efb should capture SIGTERM in addition to SIGINT(ctrl+c), because SIGTERM is the "default" graceful exit signal for kill, pkill, docker stop.

efb程序有对SIGINT（也就是ctrl+c）进行捕获。也就是说，用户按ctrl+c或者发送SIGINT给efb，稍等几秒，它都能成功”完全退出“。这一点是没问题的。

但是！
efb”并没有“对SIGTERM进行捕获。也就是说，用kill或pkill，不指定信号的情况下(默认使用SIGTERM)，efb无动于衷，导致超出了我设定的等待时间，所以我只能用强杀，所以才丢数据。

建议efb除了捕获SIGINT(ctrl+c)外，还应该捕获SIGTERM，因为SIGTERM是kill、pkill、docker stop的“默认”优雅退出信号

**Comment by blueset** [comment]
Commit 458ab2a attempted to address this issue by catching both SIGTERM and SIGINT additionally with `signal` library. 

Commit 458ab2a 尝试使用 `signal` 库附加捕获 SIGTERM 和 SIGINT 来解决此问题。
