### ISSUE TITLE
[BUG] ach_UG translation break installation

### ISSUE THREAD

**Issue by specter119** [blueset/ehForwarderBot#187]
**Describe the bug**  

get error when running msgfmt for ach_UG locale

**To Reproduce**  
1. git clone 
1. python setup build 
1. cd build/lib/ehforwarderbot/locale/ach_UG/LC_MESSAGES
1. msgfmt ehforwarderbot.po -o ehforwarderbot.mo

error message:

```plain
ehforwarderbot.po:76: 'msgid' and 'msgstr' entries do not both end with '\n'
ehforwarderbot.po:85: 'msgid' and 'msgstr' entries do not both end with '\n'
ehforwarderbot.po:94: 'msgid' and 'msgstr' entries do not both end with '\n'
ehforwarderbot.po:299: 'msgid' and 'msgstr[0]' entries do not both end with '\n'
msgfmt: found 5 fatal errors
```

EH Forwarder Bot Version: master
Python version: 3.8 
OS: archlinux

**Comment by blueset** [comment]
Thanks for the report, this is now fixed in commit 2140a34.
