### ISSUE TITLE
EWS: Unrecognised "Tencent News" (System message: newsapp) XML message format

### ISSUE THREAD

**Issue by sjtuross** [blueset/ehForwarderBot#21]
Original title:
腾讯新闻系统消息转发后显示不正常

![](http://i.imgur.com/c9NLdzi.jpg)![](http://i.imgur.com/QDHO92k.jpg)

**Comment by blueset** [comment]
Unrecognised message type sent by system account "newsapp", recognized by user as "Tencent News" or 「腾讯新闻」. As this feature is only made available to user registered in mainland China, the feature is not available to my account.

The current temporary solution is to unsubscribe or disable this feature.

**Comment by blueset** [comment]
Addressed in 1.4.4-dev.8 (deed5bb).
