### ISSUE TITLE
捐助界面里的微信账号已经不存在了，捐赠地址还有效吗？

### ISSUE THREAD

**Issue by DrayChou** [blueset/ehForwarderBot#23]
刚才捐了2.33元，捐的时候发现没有名字，但是没在意。捐完之后发现详细信息页面打不开，试着添加微信账号发现账号不存在。

请确认或者更新相关的微信账号。
![img_0914](https://cloud.githubusercontent.com/assets/760245/22850509/4e549fd6-f045-11e6-92b4-7c3bf7945269.PNG)

**Comment by blueset** [comment]
首先非常感谢您的捐赠。2.33 元已经收到。至于微信号搜不到，是我忘记启用微信号搜索了。现在已可以搜到。

感谢回馈。

_（好像微信二维码面对面付款没有显示付款来源的说）_

**Comment by DrayChou** [comment]
好的，感谢你的作品，请继续加油！

Eana Hufwe <notifications@github.com> 於 2017年2月11日 週六 上午10:37寫道：
