### ISSUE TITLE
Ignore chats

### ISSUE THREAD

**Issue by gloomy-ghost** [blueset/ehForwarderBot#30]
Not every messages on WeChat worth to forward (e.g. groups of relatives...). Since #9 is not achieved, currently I have to create a vast number of tg groups, link WeChat groups with them and mute them individually.

It would great if we could have a `/ignore` command from wechat slave channel, use same selecting progress as `/chat` but ignore their messages instead of starting a new chat. Of course we also need another command to undo the operation...

**Comment by blueset** [comment]
Firstly, my suggestion is to "unsubscribe" or "unfriend" those accounts that you may think are "worthless to be forwarded". Slave channels are made to follow the behaviour of the remote IM (WeChat in this case) as far as possible. Removing those "worthless" accounts should give you a cleaner conversation list on both of the clients.

**Comment by gloomy-ghost** [comment]
> follow the behaviour of the remote IM as far as possible.
Would be nice if it followed the mute option in WeChat...

**Comment by blueset** [comment]
@gloomy-ghost What I mean here is rather like "put out whatever the chat API feeds in". If you want to achieve what you have in WeChat on Telegram, link them to Telegram groups and mute the notification generates a much similar scenario, compare to completely discarding all messages sent from certain chats.

**Comment by gloomy-ghost** [comment]
Thanks for the new mute feature! btw I am the "anonymous EFB user" and hope another 10CNY worth a cup of coffee 😄

**Comment by blueset** [comment]
Thank you for your support to EFB, and I'm glad to hear you like it.
