### ISSUE TITLE
公众号名称与聊天群组名称一致的情况下，点击回复群组名称，也会给公众号发送相关内容。

### ISSUE THREAD

**Issue by zangev5** [blueset/ehForwarderBot#34]

**Comment by blueset** [comment]
受到微信网页版接口限制，会话的名称和备注名称是判断会话的**唯一依据**。所以目前此种情况所造成的问题暂时无解。

**Comment by liwanglin12** [comment]
那奇怪了，微信网页版原生要怎么判断发给谁？

**Comment by blueset** [comment]
微信网页版会在每次登陆后给每个会话分配一个随机的 ID。目前我们尚未找到其他更稳定的指定唯一会话的方式。详情请参见 EWS 文档的相关章节。

**Comment by liwanglin12** [comment]
EFB一样可以通过随机生成id来解决该问题吧？

Eana Hufwe <notifications@github.com>于2017年7月22日周六 上午6:20写道：

**Comment by blueset** [comment]
@liwanglin12 这个的确考虑过，不过对于断线之后重新登录时会话的重新匹配，尤其是群成员、会话名称、备注名称等的匹配，目前还没有想到较为可行的方案。

**Comment by liwanglin12** [comment]
对于这个issue，公众号在网页端都有分组提示，理论上应该能识别出公众号和群聊的类型差别来判断吧。
对于实在无法判断的，例如两个相同名字的群聊，空名字群聊，名字被修改的群聊，在首次链接到群时可以让bot对群内发送一条UUID信息，在每次重连后提供按钮要求用户介入确认。
这会有一点麻烦，但是至少能用了。
