### ISSUE TITLE
微信二维码不能显示

### ISSUE THREAD

**Issue by l0o0** [blueset/ehForwarderBot#36]
你好，按照https://blog.1a23.com/2017/01/09/EFB-How-to-Send-and-Receive-Messages-from-WeChat-on-Telegram-zh-CN/  上的链接，尝试装了下个微信bot，不过运行
`python3 daemon.py start`后就一直显示：
> pid: 24780
   Output is saved to 'EFB.log', showing output now.       
   Press ^C (Control+C on Mac, Ctrl+C otherwise) to hide.   

VPS上安装的Ubuntu14.04，自己安装了Python3.5。

不知是何原因

**Comment by blueset** [comment]
请在 `daemon.py` 的同一目录下尝试重新启动。若失败，尝试直接运行 `python3 main.py`。
