### ISSUE TITLE
Send QR codes to Telegram master channel

### ISSUE THREAD

**Issue by PeterCxy** [blueset/ehForwarderBot#37]
The WeChat slave needs rescanning the QR code every several days. It is painful because the QR is only thrown into the command line, and I'll have to ssh onto the server for rescanning every time. It will be more convenient if the slave can forward the QR code to Telegram master channel so that I can just save & scan from WeChat.

**Comment by blueset** [comment]
In cases where the environment is configured properly, EWS should be able to run for months without being disconnected. Even EWS WeChat Web is being disconnected, it should be able to send you the QR code for reauthentication through EFB framework, so there is no need to SSH everytime when WeChat Web is disconnected.

**Comment by B44ST** [comment]
I'd like to have this feature too.
