### ISSUE TITLE
网络容错

### ISSUE THREAD

**Issue by gloomy-ghost** [blueset/ehForwarderBot#38]
最近 telegram 的 API 时不时抽一下，然后向微信发的消息就悄无声息地被吞了…… telegram 上给 bot 发消息会被标为已读但是没有任何响应，微信上则依然显示已经登录 Web 版。

Log:
https://gist.github.com/gloomy-ghost/5c1bc2037f033c6ba7142f876e3838cf

**Comment by blueset** [comment]
网络连接和重试的问题是由上游库控制的，ETM 这边类似错误可以报给 [python-telegram-bot/python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot).
