### ISSUE TITLE
提个小小的建议

### ISSUE THREAD

**Issue by dysl357085918** [blueset/ehForwarderBot#39]
比如我有一些工作的群，然后我单独把这些群link到一个group里面，日常非工作时段，把这个group开启免打扰，工作时再打开提醒。但是因为群聊中日常会有人过生日。微信群聊的名称就改了，就要一次次重新link，请问有没有什么解决的办法，谢谢。

**Comment by blueset** [comment]
微信会话名称变化会导致其在 EWS 的唯一 ID 随之变化。这是已知问题。详情请参见文档。
