### ISSUE TITLE
Most time could not receive message

### ISSUE THREAD

**Issue by mengyyy** [blueset/ehForwarderBot#4]
And when receivemessage is wechat emoji it show "Error: Empty Image received. (MS01)" 
This message was one of two message i received another waas from group chat.
These two message receive when the bot was force stop.

**Comment by mengyyy** [comment]
After delete the bot fro mgroup chat in telegram .Readd the bot later , i found the linked people  still could not unlink and could not relink .

**Comment by blueset** [comment]
Fixed in 70795d1 .

**Comment by blueset** [comment]
Copyright protected sticker sets are not available to Web WeChat, leading to an empty sticker file to be delivered.

Added to docs "EWS: Known issues" in 70795d1 .

Second issue is duplicate in #3.
