### ISSUE TITLE
ImportError: No module named 'config'

### ISSUE THREAD

**Issue by livc** [blueset/ehForwarderBot#40]
➜  ehForwarderBot git:(master)   python3 main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import config
ImportError: No module named 'config'

ubuntu 16

I have installed the  dependencies  as https://ehforwarderbot.readthedocs.io/en/latest/installation/

**Comment by blueset** [comment]
`config` is not a Python dependency, but the `config.py` file in the root directory.

Please set up your `config.py` according to `config.sample.py` or [the documentation](https://ehforwarderbot.readthedocs.io/en/latest/getting-started/).

**Comment by livc** [comment]
Thanks for the reply.
