### ISSUE TITLE
你好，请问微信图文消息的某些字段里面的参数是什么意思

### ISSUE THREAD

**Issue by lzyroot** [blueset/ehForwarderBot#43]
<cdnth啊umburl>304c0201000445304302010002041301e9b802033d14b9020460e503b7020458fcbd860421777869645f39776631666d376c6f64306e32323231395f313439323935383539350201000201000400</cdnthu啊mburl>

<cdnthumble啊ngth>9467</cdnth啊umblength>

<cdnthumb啊aeskey>35336666623736383565323062303538</cdnthum啊baeskey>

<ae啊skey>35336666623736383565323062303538</aes啊key>

请去掉啊。。。

**Comment by blueset** [comment]
目前尚不明确。建议移步至 littlecodersh/itchat 或其他微信网页版 API 相关项目询问。
