### ISSUE TITLE
OSError: cannot identify image file 'storage/eh_telegram_master/...'

### ISSUE THREAD

**Issue by rosuH** [blueset/ehForwarderBot#44]
This error occurred when I want to send a Telegram's sticker.
OS:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
hardware-platform : 86_64 GNU/Linux
```
- I can receive all messages from Wechat included texts and images.
- I can send text messages in Telegram.
- All dependencies may prepared.

Here is the log  when I want to send a Telegram's sticker:
```shell
2017-04-27 08:09:45,902: telegram.ext.dispatcher [ERROR]
    An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/messagehandler.py", line 123, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/a/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 1128, in msg
    return self.process_telegram_message(bot, update)
  File "/home/a/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 1340, in process_telegram_message
    slave_msg = self.slaves[channel].send_message(m)
  File "/home/a/ehForwarderBot/plugins/eh_wechat_slave.py", line 666, in send_message
    img = Image.open(msg.path)
  File "/usr/local/lib/python3.4/dist-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'storage/eh_telegram_master/Sticker_-160796490_330_1493251785.obj'

```

- - - - - 
My English is not very good. Here is the Chinese version:

当我发送 Telegram 的贴纸的时候，发生了这个错误。
当程序启动之后，我可以正常接收来自微信的一切消息，包括表情、文字以及图片等。
我也可以从 Telegram 发送文字消息，但是无法发送**贴图**或者**图片**。

Thanks!

**Comment by vjdsnagiurt** [comment]
Try to upgrade your python to python3.5 or greater.

**Comment by blueset** [comment]
Can you try to upload your `storage/eh_telegram_master/Sticker_-160796490_330_1493251785.obj`?

**Comment by rosuH** [comment]
@vjdsnagiurt I had tried  to upgrade my Python version.
Type `Python version`:
```
Python 3.5.1
```
After that, I also reinstall all  dependencies.
```
nano is already the newest version.
git is already the newest version.
libmagic1 is already the newest version.
python3-pip is already the newest version.
ffmpeg is already the newest version.
libopus0 is already the newest version.
python3.5 is already the newest version.

```
```
Successfully installed Pillow-4.1.0 certifi-2017.4.17 decorator-4.0.11 docutils-0.13.1 future-0.16.0 imageio-2.1.2 itchat-1.3.5 lockfile-0.12.2 moviepy-0.2.3.2 numpy-1.12.1 olefile-0.44 peewee-2.9.2 pydub-0.18.0 pypng-0.0.18 pyqrcode-1.2.1 python-daemon-2.1.2 python-magic-0.4.13 python-telegram-bot-5.3.1 requests-2.13.0 tqdm-4.11.2 urllib3-1.20 xmltodict-0.10.2
```
**However, it did not work**.
- - - - -

@blueset There are several file formats in `eh_telegram_master`.
```
Sticker_-160796490_227_1493219988.exe  Sticker_-160796490_436_1493259063.obj
Sticker_-160796490_232_1493220087.exe  Sticker_-160796490_518_1493280629.obj
Sticker_-160796490_233_1493220112.exe  Sticker_-160796490_592_1493294543.o
Sticker_-160796490_237_1493220146.exe  Sticker_-160796490_600_1493295370.o
Sticker_-160796490_239_1493220159.exe  Sticker_-191478191_369_1493255130.obj
Sticker_-160796490_306_1493221968.exe  Sticker_-191478191_379_1493255260.obj
Sticker_-160796490_326_1493251561.exe  Sticker_221798031_182_1493217871.exe
Sticker_-160796490_330_1493251785.obj  Sticker_221798031_241_1493220192.exe

```
I had uploaded all file in `eh_telegram_master.7z` and single `obj` file.

- - - - -
Thanks!

**Comment by blueset** [comment]
@rosuH Do you have the latest version of EFB (1.6.1) installed? The issue seems to be on the MIME type of the file. This is solved in about 1.5.x version. 

Before you upgrade, please read the notice in release note for each minor version.

**Comment by rosuH** [comment]
@blueset Yes, it's the latest version.

**Comment by blueset** [comment]
Can you check that you have `libwebp-dev` (or other corresponding package in your disto) installed before `pillow`?
There seems to have no issue with your file.

**Comment by rosuH** [comment]
I had install `libwebp-dev` and I didn't work...

**Comment by blueset** [comment]
@rosuH Maybe you can try to raise the issue to https://github.com/python-pillow/Pillow, and bring along with your Stickers- files. 

Those files should be opened with PIL on a properly configured environment.

shell
$ for i in Sticker*; do python3 -c "from PIL import Image; x = Image.open('$i'); print(x.format)"; done;
WEBP
WEBP
WEBP
WEBP
WEBP
WEBP
WEBP
WEBP
WEBP
WEBP
WEBP
WEBP
WEBP
WEBP

**Comment by rosuH** [comment]
@blueset I got you.  I will try to raise the issue.
Finally, ask again, Can `Pillow` open a file with the suffix `.exe | .obj | .o`?

I do not know much about python(also for English XD ). Please do not mind my ignorance.

**Comment by rosuH** [comment]
@blueset I had raised an [issue](https://github.com/python-pillow/Pillow/issues/2498). However they said it may not their issue.
If this problem is very strange and particularity, may be we can just let it go?

**Comment by blueset** [comment]
我在这边的测试机上面用你的文件试过的，可以正常读取。初步怀疑是 WebP 库或者 Pillow 阶段的问题。如果环境配置不成功的话可以尝试使用社区维护的 EFB Docker 镜像。

**Comment by rosuH** [comment]
@blueset 非常感谢您的辛苦跟进。
