### ISSUE TITLE
无法发送消息？

### ISSUE THREAD

**Issue by LanHao0** [blueset/ehForwarderBot#46]
/chat 无法发送消息
Message is not sent. (MN01)

{'LocalID': '', 'MsgID': '', 'BaseResponse': {'RawMsg': '', 'ErrMsg': '', 'Ret': 1102}}

**Comment by blueset** [comment]
微信方面提出的错误提示，目前没有找到导致此类问题的原因。
可以尝试的 Workaround：从微信手机端登出网页版，并重新登录。

**Comment by LanHao0** [comment]
咳咳！突然好了！重登了一下 可能是VPS网络原因吧
