### ISSUE TITLE
daemon启动报错

### ISSUE THREAD

**Issue by GEM7** [blueset/ehForwarderBot#47]
你好，我按照文档配置了config.py文件，但是执行daemon.py文件时出现以下错误信息。我是完全从文档中复制来的。

Traceback (most recent call last):
  File "main.py", line 131, in <module>
    init()
  File "main.py", line 83, in init
    obj = getattr(__import__(i[0], fromlist=i[1]), i[1])
ModuleNotFoundError: No module named 'plugins.eh_demo_slave'

我的config.py相关字段为
master_channel = "plugins.eh_demo_master", "DemoMasterChannel"
slave_channels = [
    ("plugins.eh_demo_slave", "DemoSlaveChannel"),
    ("plugins.eh_random_slave", "RandomSlaveChannel"),
    ("plugins.eh_mychat_slave", "MyChatSlaveChannel")
]

**Comment by Anyfc** [comment]
请问这个：plugins.eh_demo_slave 去哪里下载？翻了教程半天都没有找到

**Comment by GEM7** [comment]
这个“plugins.eh_demo_slave”是不存在的，这个是作者举的一个例子。master_channel的配置应该是`master_channel = "plugins.eh_telegram_master", "TelegramChannel"`slive_channel的配置应该是`slave_channels = [("plugins.eh_wechat_slave", "WeChatChannel")]
`

**Comment by Anyfc** [comment]
多谢，另外还想请教下：
    [0;37;46m Initializing slave ('plugins.eh_wechat_slave', 'WeChatChannel')... [0m
Traceback (most recent call last):
  File "main.py", line 132, in <module>
    init()
  File "main.py", line 83, in init
    obj = getattr(__import__(i[0], fromlist=i[1]), i[1])
  File "/root/ehForwarderBot/plugins/eh_wechat_slave.py", line 13, in <module>
    import magic
ImportError: No module named 'magic'

这个magic 模块如何安装，我已经使用pip install pythc-magic 安装成功了，但还是提示上面的错误

**Comment by GEM7** [comment]
可能是pip 版本和 当前使用的python不对应。举个例子如果你当前python版本是3.5 那么与其对应的pip命令应该是 pip3.5

**Comment by Anyfc** [comment]
@GEM7 是pip版本和 当前使用的python不对应 这个问题，改过之后正常了，不过后面有个python模块安装不上，安装过程一直被kill掉，不知道什么原因。

ps：官方安装说明太混乱了，东一片西一片的，python3 daemon.py start 这条命令执行了N次，都还提示缺少依赖。
