### ISSUE TITLE
希望能增加转发IRC频道功能

### ISSUE THREAD

**Issue by LanHao0** [blueset/ehForwarderBot#49]
本来想用这个wechat-telegram-irc-qq的，然而telegram bot之间无法接收消息
希望可以加一个把微信群消息发到指定IRC频道里的功能

**Comment by blueset** [comment]
EH Forwarder Bot 是一个开放的框架，欢迎有兴趣的朋友来开发各种 Channel 以对接不同平台。

关于群组间同步消息的功能，请参见以下文章：  
https://blog.1a23.com/2017/01/28/Idea-Group-Chat-Tunneling-Sync-with-EH-Forwarder-Bot/
