### ISSUE TITLE
关于从tg传文件到微信

### ISSUE THREAD

**Issue by trysh** [blueset/ehForwarderBot#51]
文件名是 hh工作簿1.xlsx
出现在微信聊天记录里是 hh工作簿1.xlsx.h

```
2017-06-02 19:33:49,062: telegram.ext.dispatcher [DEBUG]
    Processing Update: {'update_id': 336460739, 'message': {'chat': {'type': 'group', 'id': -201032932, 'first_name': '', 'last_name': '', 'username': '', 'all_members_are_admins': False, 'title': '偏锋测试'}, 'new_chat_title': '', 'supergroup_chat_created': False, 'message_id': 4672, 'migrate_from_chat_id': 0, 'date': 1496403228, 'text': '', 'delete_chat_photo': False, 'new_chat_photo': [], 'caption': '66666666666', 'document': {'mime_type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'file_size': 10380, 'file_name': 'hh工作簿1.xlsx', 'file_id': 'BQADBQADBgADiOSQVVJ5sB0hVNf4Ag'}, 'group_chat_created': False, 'from': {'id': 332872098, 'last_name': '', 'username': 'trysh86', 'first_name': 'trysh', 'type': ''}, 'migrate_to_chat_id': 0, 'photo': [], 'channel_chat_created': False, 'entities': []}}
2017-06-02 19:33:49,063: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    ----
Msg from tg user:
{'chat': {'type': 'group', 'id': -201032932, 'first_name': '', 'last_name': '', 'username': '', 'all_members_are_admins': False, 'title': '偏锋测试'}, 'new_chat_title': '', 'supergroup_chat_created': False, 'message_id': 4672, 'migrate_from_chat_id': 0, 'date': 1496403228, 'text': '', 'delete_chat_photo': False, 'new_chat_photo': [], 'caption': '66666666666', 'document': {'mime_type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'file_size': 10380, 'file_name': 'hh工作簿1.xlsx', 'file_id': 'BQADBQADBgADiOSQVVJ5sB0hVNf4Ag'}, 'group_chat_created': False, 'from': {'id': 332872098, 'last_name': '', 'username': 'trysh86', 'first_name': 'trysh', 'type': ''}, 'migrate_to_chat_id': 0, 'photo': [], 'channel_chat_created': False, 'entities': []}
2017-06-02 19:33:49,064: peewee [DEBUG]
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS t1 WHERE ("t1"."master_uid" = ?)', ['eh_telegram_master.-201032932'])
2017-06-02 19:33:49,064: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    ----
Msg from tg user:
{'chat': {'type': 'group', 'id': -201032932, 'first_name': '', 'last_name': '', 'username': '', 'all_members_are_admins': False, 'title': '偏锋测试'}, 'new_chat_title': '', 'supergroup_chat_created': False, 'message_id': 4672, 'migrate_from_chat_id': 0, 'date': 1496403228, 'text': '', 'delete_chat_photo': False, 'new_chat_photo': [], 'caption': '66666666666', 'document': {'mime_type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'file_size': 10380, 'file_name': 'hh工作簿1.xlsx', 'file_id': 'BQADBQADBgADiOSQVVJ5sB0hVNf4Ag'}, 'group_chat_created': False, 'from': {'id': 332872098, 'last_name': '', 'username': 'trysh86', 'first_name': 'trysh', 'type': ''}, 'migrate_to_chat_id': 0, 'photo': [], 'channel_chat_created': False, 'entities': []}
2017-06-02 19:33:49,065: peewee [DEBUG]
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS t1 WHERE ("t1"."master_uid" = ?)', ['eh_telegram_master.-201032932'])
2017-06-02 19:33:49,065: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    Destination chat = eh_wechat_slave.2443522499
2017-06-02 19:33:49,066: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    Msg type: Document
2017-06-02 19:33:49,066: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    tg: Document file received
2017-06-02 19:33:50,622: plugins.eh_telegram_master.TelegramChannel [WARNING]
    File storage/eh_telegram_master/File_-201032932_4672_1496403230 with mime application/vnd.openxmlformats-officedocument.spreadsheetml.sheet has no matching extensions.
2017-06-02 19:33:56,081: plugins.eh_wechat_slave.WeChatChannel [INFO]
    Sending message to WeChat:
Target-------
uid: 2443522499
UserName: @@456ee3a71ab6b7e6944280d95bbf5d039ddba11526c32eaa7298edd37d67cc69
NickName: 
Type: File
Text: 66666666666
2017-06-02 19:33:56,082: plugins.eh_wechat_slave.WeChatChannel [INFO]
    Sending File to WeChat
FileName: 66666666666
Path: storage/eh_telegram_master/File_-201032932_4672_1496403230.unknown
Filename: hh工作簿1.xlsx
2017-06-02 19:33:56,082: itchat [DEBUG]
    Request to upload a file: storage/eh_telegram_master/File_-201032932_4672_1496403230.unknown
2017-06-02 19:33:56,418: itchat [DEBUG]
    Request to send a text message to @@456ee3a71ab6b7e6944280d95bbf5d039ddba11526c32eaa7298edd37d67cc69: 66666666666
2017-06-02 19:33:56,715: peewee [DEBUG]
    ('INSERT INTO "msglog" ("master_msg_id", "slave_message_id", "text", "slave_origin_uid", "slave_origin_display_name", "slave_member_uid", "slave_member_display_name", "msg_type", "sent_to", "time") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', ['-201032932.4672', '2865668647267531631', '66666666666', 'eh_wechat_slave.2443522499', '__chat__', None, None, 'File', 'slave', datetime.datetime(2017, 6, 2, 19, 33, 56, 714519)])
```

**Comment by vjdsnagiurt** [comment]
不能传中文名文件，改成英文就行了。

**Comment by trysh** [comment]
不。改成英文名也会有几率出现这个问题

**Comment by blueset** [comment]
已尝试多种文件名组合，但均未能重现。请检查相关依赖是否已更新到最新版本
```bash
pip3 install -U -r requirements.txt
```

**Comment by RoyXiang** [comment]
@blueset 无法复现的话… 可以找找看复现环境里有没有其他地方有 `mime.types` 文件… `python` 的 `mimetypes` 库会自动查找文件系统里的这个文件去猜测文件后缀的… 这里的错误日志里猜测的文件后缀是 `.unknown`

**Comment by blueset** [comment]
@RoyXiang 目前版本的扩展名、MIME 类型工作逻辑是这样的：
- 下载文件时从服务器获取 MIME 类型，若服务器未提供，则使用 Magic 库猜测 MIME
- 根据类型猜测扩展名，并将其作为本地扩展名使用。
- 下载完成后将本地文件路径、MIME、源文件名一同封装进 `EFBMsg` 对象内。
- 接收方根据文件信息指定发送方式：
  - 对于微信从端来说，会直接使用「源文件名」作为发送文件的名称，然后从「本地文件路径」获取数据。

流程中应该是没有用到本地文件的扩展名。

顺便，我在测试的时候，本地文件的扩展名也是 `.unknown`。

**Comment by trysh** [comment]
@blueset 
总算重现并精准地定位log了
文件名是：Current Weather Image - Los Narejos in the Evening (a32867db0991c704cfa10ca7a5c8e30b0cb972ac).jpg
用tg发送到微信的“文件助手”(filehelper)
“说明文字”填的是“7777777”
不勾选压缩
在微信界面聊天记录中出现的是
一个文件，来自微信网页版
文件名是Current.....jpg.u     <----注意这里多了“.u”
底下一条纯文字信息：7777777

trys2163@instance-3:~/ehForwarderBot$ python3 daemon.py restart -vv
Restarting EFB daemon (1)
PID: 5158
Name: 2967793561
   Output is saved to 'EFB.log', showing output now.       
   Press ^C (Control+C on Mac, Ctrl+C otherwise) to hide.  

2017-06-08 19:40:09,254: itchat [DEBUG]
    loading login status succeeded.
2017-06-08 19:40:09,255: plugins.eh_wechat_slave.WeChatChannel [INFO]
    EWS Inited!!!
---
2017-06-08 19:40:09,256: ehForwarderBot [CRITICAL]
     Slave channel WeChat Slave (eh_wechat_slave) initialized. 
2017-06-08 19:40:09,256: ehForwarderBot [CRITICAL]
     Initializing master ('plugins.eh_telegram_master', 'TelegramChannel')... 
2017-06-08 19:40:09,391: peewee [DEBUG]
    ('SELECT name FROM sqlite_master WHERE type = ? ORDER BY name;', ('table',))
2017-06-08 19:40:09,392: peewee [DEBUG]
    ('PRAGMA table_info("msglog")', None)
2017-06-08 19:40:09,392: peewee [DEBUG]
    ('SELECT name FROM sqlite_master WHERE type = ? ORDER BY name;', ('table',))
2017-06-08 19:40:09,842: telegram.ext.dispatcher [DEBUG]
    Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x7ff3a36fac88>
2017-06-08 19:40:10,897: ehForwarderBot [CRITICAL]
     Master channel Telegram Master (eh_telegram_master) initialized. 
2017-06-08 19:40:10,898: ehForwarderBot [CRITICAL]
     All channels initialized. 
2017-06-08 19:40:10,898: JobQueue [DEBUG]
    JobQueue thread started
2017-06-08 19:40:10,899: telegram.ext.updater [DEBUG]
    dispatcher - started
2017-06-08 19:40:10,899: telegram.ext.updater [DEBUG]
    updater - started
2017-06-08 19:40:10,899: telegram.ext.updater [DEBUG]
    Updater thread started
2017-06-08 19:40:10,901: telegram.ext.dispatcher [DEBUG]
    Dispatcher started
2017-06-08 19:40:28,430: telegram.ext.dispatcher [DEBUG]
    Processing Update: {'update_id': 336460857, 'message': {'new_chat_members': [], 'photo': [], 'entities': [], 'channel_chat_created': False, 'delete_chat_photo': False, 'supergroup_chat_created': False, 'date': 1496922028, 'from': {'id': 332872098, 'username': 'trysh86', 'first_name': 'trysh', 'language_code': 'zh'}, 'new_chat_member': None, 'caption': '7777777', 'group_chat_created': False, 'message_id': 5219, 'chat': {'title': '微信文件助手', 'id': -183610074, 'all_members_are_administrators': True, 'type': 'group'}, 'document': {'thumb': {'file_size': 2211, 'width': 90, 'file_id': 'AAQFABP5qMsyAATYAAGmOjw3HazuNgACAg', 'height': 50}, 'mime_type': 'image/jpeg', 'file_size': 256537, 'file_name': 'Current_Weather_Image_Los_Narejos.jpg', 'file_id': 'BQADBQADEgADJ2LJVV0PTnai4eM7Ag'}, 'new_chat_photo': []}}
2017-06-08 19:40:28,430: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    ----
Msg from tg user:
{'new_chat_members': [], 'photo': [], 'entities': [], 'channel_chat_created': False, 'delete_chat_photo': False, 'supergroup_chat_created': False, 'date': 1496922028, 'from': {'id': 332872098, 'username': 'trysh86', 'first_name': 'trysh', 'language_code': 'zh'}, 'new_chat_member': None, 'caption': '7777777', 'group_chat_created': False, 'message_id': 5219, 'chat': {'title': '微信文件助手', 'id': -183610074, 'all_members_are_administrators': True, 'type': 'group'}, 'document': {'thumb': {'file_size': 2211, 'width': 90, 'file_id': 'AAQFABP5qMsyAATYAAGmOjw3HazuNgACAg', 'height': 50}, 'mime_type': 'image/jpeg', 'file_size': 256537, 'file_name': 'Current_Weather_Image_Los_Narejos.jpg', 'file_id': 'BQADBQADEgADJ2LJVV0PTnai4eM7Ag'}, 'new_chat_photo': []}
2017-06-08 19:40:28,431: peewee [DEBUG]
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS t1 WHERE ("t1"."master_uid" = ?)', ['eh_telegram_master.-183610074'])
2017-06-08 19:40:28,432: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    ----
Msg from tg user:
{'new_chat_members': [], 'photo': [], 'entities': [], 'channel_chat_created': False, 'delete_chat_photo': False, 'supergroup_chat_created': False, 'date': 1496922028, 'from': {'id': 332872098, 'username': 'trysh86', 'first_name': 'trysh', 'language_code': 'zh'}, 'new_chat_member': None, 'caption': '7777777', 'group_chat_created': False, 'message_id': 5219, 'chat': {'title': '微信文件助手', 'id': -183610074, 'all_members_are_administrators': True, 'type': 'group'}, 'document': {'thumb': {'file_size': 2211, 'width': 90, 'file_id': 'AAQFABP5qMsyAATYAAGmOjw3HazuNgACAg', 'height': 50}, 'mime_type': 'image/jpeg', 'file_size': 256537, 'file_name': 'Current_Weather_Image_Los_Narejos.jpg', 'file_id': 'BQADBQADEgADJ2LJVV0PTnai4eM7Ag'}, 'new_chat_photo': []}
2017-06-08 19:40:28,432: peewee [DEBUG]
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS t1 WHERE ("t1"."master_uid" = ?)', ['eh_telegram_master.-183610074'])
2017-06-08 19:40:28,433: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    Destination chat = eh_wechat_slave.filehelper
2017-06-08 19:40:28,434: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    Msg type: Document
2017-06-08 19:40:28,434: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    tg: Document file received
2017-06-08 19:40:33,474: plugins.eh_wechat_slave.WeChatChannel [INFO]
    Sending message to WeChat:
Target-------
uid: filehelper
UserName: filehelper
NickName: 
Type: File
Text: 7777777
2017-06-08 19:40:33,474: plugins.eh_wechat_slave.WeChatChannel [INFO]
    Sending File to WeChat
FileName: 7777777
Path: storage/eh_telegram_master/File_-183610074_5219_1496922030.jpeg
Filename: Current_Weather_Image_Los_Narejos.jpg
2017-06-08 19:40:33,474: itchat [DEBUG]
    Request to upload a file: storage/eh_telegram_master/File_-183610074_5219_1496922030.jpeg
2017-06-08 19:40:34,190: itchat [DEBUG]
    Request to send a text message to filehelper: 7777777
2017-06-08 19:40:34,322: peewee [DEBUG]
    ('INSERT INTO "msglog" ("master_msg_id", "slave_message_id", "text", "slave_origin_uid", "slave_origin_display_name", "slave_member_uid", "slave_member_display_name", "msg_type", "sent_to", "time") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', ['-183610074.5219', '8370918774235372525', '7777777', 'eh_wechat_slave.filehelper', '__chat__', None, None, 'File', 'slave', datetime.datetime(2017, 6, 8, 19, 40, 34, 321844)])
2017-06-08 19:40:34,454: plugins.eh_wechat_slave.wechat_msg_meta [DEBUG]
    me, False

**Comment by blueset** [comment]
Fixed in 1.5.3.
