### ISSUE TITLE
[Feature request]合并公众号发的一组消息

### ISSUE THREAD

**Issue by CzBiX** [blueset/ehForwarderBot#53]
![image](https://cloud.githubusercontent.com/assets/760097/26812858/e055b048-4aac-11e7-9170-6a2892c68284.png)

**Comment by blueset** [comment]
由于目前没有发现其他平台的应用，EFB 框架目前没有支持「多链接式链接消息」的计划。
如有兴趣，请尝试创建框架的分支并进行修改。
