### ISSUE TITLE
EWS: Redirect user to mobile for notified unsupported message types.

### ISSUE THREAD

**Issue by fanzibin** [blueset/ehForwarderBot#54]
微信 “合并转发”消息到telegram，telegram没有消息的提示，但是如果“逐条转发”消息提示正常

谢谢

**Comment by blueset** [comment]
合并转发的消息微信网页版并不能正常收到，故 EWS 也无法支持该类型。

**Comment by fanzibin** [comment]
恩，刚试了，确实 微信网页版也不能正常收到，但是微信网页版会提示 
[收到一条网页版微信暂不支持的消息类型，请在手机上查看]

那么telegram端 也能不能增加这样一条提示呢？不然很容易漏掉消息，如果telegram端这样提示了，至少可以知道别人发了消息过来，不然完全不知道有消息，请考虑一下，谢谢

**Comment by blueset** [comment]
Should be fixed in EWS v2.

**Comment by blueset** [comment]
This issue was moved to blueset/efb-wechat-slave#8
