### ISSUE TITLE
可否更新一下中文安装说明

### ISSUE THREAD

**Issue by Anyfc** [blueset/ehForwarderBot#56]
https://blog.1a23.com/2017/01/09/EFB-How-to-Send-and-Receive-Messages-from-WeChat-on-Telegram-zh-CN/ 
这个地址的教程已经标注了 过时
网上能找到的都是这个过时的版本，希望可以更新一下

**Comment by blueset** [comment]
相关安装说明请参照[项目文档](https://ehforwarderbot.readthedocs.io/en/latest/)和相应 Channel 的说明页面，谢谢。

**Comment by LanHao0** [comment]
http://blog.lanhaoo.club/2017/05/19/%E5%BE%AE%E4%BF%A1-telegram-%E4%BA%92%E8%81%94%EF%BC%88%E4%B8%AD%E6%96%87%EF%BC%89/
