### ISSUE TITLE
python telegram bot

### ISSUE THREAD

**Issue by reza-mizaee** [blueset/ehForwarderBot#57]
hello.

```
import telegram
bot = telegram.Bot(token='token')
```
I am getting following Error:
AttributeError: 'module' object has no attribute 'Bot'

and
```
dir(Telegram)
```
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']

**Comment by blueset** [comment]
It seems that you made a typo in the `dir` command.
For any [`python-telegram-bot`](https://github.com/python-telegram-bot/python-telegram-bot) related issues, please visit [their issue page](https://github.com/python-telegram-bot/python-telegram-bot/issues) for help.
