### ISSUE TITLE
如何指定某个微信群禁止转发到 Telegram？

### ISSUE THREAD

**Issue by DoraJDJ** [blueset/ehForwarderBot#60]
由于学校实习需要，强制使用微信，因此在几周前我在网上找到这个项目并使用它来将微信群的消息转发到 Telegram。

但是使用久了我发现一个问题：它不能指定某个微信群禁止转发，我只能将机器人拉到某个群里，指定该机器人能够转发哪个微信群或联系人地消息。

这个问题让我造成了很大的困扰，比如毫无必要的公众号推送，还有一些亲戚群里经常出现的不适合公众场合访问的擦边球内容，甚至是可能会被认为是 child p0rn 的儿童果体照（比如小孩子洗澡的照片）都会直接通过机器人推送到我的 Telegram 里。

![tim 20170630221126](https://user-images.githubusercontent.com/3974330/27739419-159c7b96-5de1-11e7-8b64-5732f66d3f7b.png)

因为这个问题我刚才紧急停止了机器人的工作。

我现在想询问下，现在有什么方法能够选择某个微信群组或联系人**禁止转发到 Telegram**？如果没有，何时能够将这个功能完善好？

**Comment by blueset** [comment]
EFB 的行为设计目前是原样转发所有能够收到并能够支持的从端消息。对于并不再使用的会话（包括用户会话、群组、微信公众号等）。我们的建议是在消息源移除或退出该会话。

如果需要更加细致的过滤的话（例如变更或阻止符合条件的部分信息），正在筹备中的 EFB v2 将增加中间件（Middleware）功能，能够让框架程序化的处理来往的消息。与此同时，ETM 也内置了 mute 按键。

**Comment by twotwo** [comment]
v2计划什么时候发布呢？
强烈需要“停止转发微信公众号的消息”的功能。

**Comment by BillScott1024** [comment]
同需要过滤功能，按类型过滤去除公众号
