### ISSUE TITLE
如何在一台vps上同时运行两个或两个以上的ehForwarderBot

### ISSUE THREAD

**Issue by Anyfc** [blueset/ehForwarderBot#61]
vps的配置足够，想同时提供给朋友使用

**Comment by blueset** [comment]
（适用于 v1.x）

共用一个主端：参照 Wiki
多个主端：重新克隆一份项目即可

**Comment by Anyfc** [comment]
@blueset 请问下，共用一个主端的话，telegrambot也是共用的吗？
