### ISSUE TITLE
Input “python3 main.py” ,Keep prompting "Please immediately turn off this EFB instances. Another bot instance or webhook detected."

### ISSUE THREAD

**Issue by vievenvua** [blueset/ehForwarderBot#62]
> # python3 daemon.py status
> PID: 5810, CMD: '/usr/bin/python3 main.py'
> Logfile: 'EFB.log'
> Name: xxxxxxxxxx(**May be involved in privacy, so hidden**)
> Start at: "2017-06-28 06:06:56"
> 
> # python3 main.py
> 2017-07-03 01:55:47,488: ehForwarderBot [CRITICAL]
>      Initializing slave ('plugins.eh_wechat_slave', 'WeChatChannel')... 
> 2017-07-03 01:55:52,546: ehForwarderBot [CRITICAL]
>      Slave channel WeChat Slave (eh_wechat_slave) initialized. 
> 2017-07-03 01:55:52,548: ehForwarderBot [CRITICAL]
>      Initializing master ('plugins.eh_telegram_master', 'TelegramChannel')... 
> 2017-07-03 01:55:54,451: ehForwarderBot [CRITICAL]
>      Master channel Telegram Master (eh_telegram_master) initialized. 
> 2017-07-03 01:55:54,453: ehForwarderBot [CRITICAL]
>      All channels initialized. （**Here when the telegram has been able to send and receive messages**）
> 2017-07-03 01:55:55,902: telegram.ext.updater [ERROR]
>     Error while getting Updates: Conflict: terminated by other long poll or webhook (409)
> 2017-07-03 01:55:55,905: plugins.eh_telegram_master.TelegramChannel [CRITICAL]
>     Please immediately turn off this EFB instances.
> Another bot instance or webhook detected.
> 2017-07-03 01:55:58,708: telegram.ext.updater [ERROR]
>     Error while getting Updates: Conflict: terminated by other long poll or webhook (409)
> 2017-07-03 01:55:58,709: plugins.eh_telegram_master.TelegramChannel [CRITICAL]
>     Please immediately turn off this EFB instances.
> Another bot instance or webhook detected.
> ^C（**In this time when the telegram can not receive the messages**）

Attach this, hope he is useful

> # cat EFB.log
> 2017-07-03 01:35:09,996: telegram.ext.updater [ERROR]
>     Error while getting Updates: Conflict: terminated by other long poll or webhook (409)
> 2017-07-03 01:35:09,997: plugins.eh_telegram_master.TelegramChannel [CRITICAL]
>     Please immediately turn off this EFB instances.
> Another bot instance or webhook detected.

**Comment by blueset** [comment]
Most likely you didn't completely turn off the other EFB instance before turning on this one.
Make sure you only have one program using the bot token at one time.
