### ISSUE TITLE
link到group 后发送消息无反应

### ISSUE THREAD

**Issue by laihuchun** [blueset/ehForwarderBot#66]
link到group 后发送消息无反应
修改bot隐私设置往group里发送消息提示This group is not linked to any chat. (UC06)
修改bot隐私设置后发送消息无反应,且微信没有发出消息.

**Comment by blueset** [comment]
请尝试在修改 bot 隐私设置后使用 `/link` 绑定会话。

**Comment by laihuchun** [comment]
已经修改过bot隐私设置了   。在问题描述里说明了啊，但是还是不能绑定会话。不知道是哪里操作不对

**Comment by laihuchun** [comment]
botfather 里面有个group enable 机器人加入到群组 打开就好了.
