### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by Gontid** [blueset/ehForwarderBot#68]
Doesn't seem to affect functionality but I saw the following in the log file. Can someone explain what is wrong? Running ehForwarderBot on Centos 7.

```
return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/lib/python3.6/site-packages/peewee.py", line 3775, in execute_sql
    self.commit()
  File "/usr/lib/python3.6/site-packages/peewee.py", line 3598, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/lib/python3.6/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: database is locked
```

Appreciate your help!

**Comment by blueset** [comment]
Can you reproduce this error? If so, what are the steps to reproduce it?

**Comment by Gontid** [comment]
It shows up immediately after QR code is scanned and WeChat login is complete.

**Comment by LiCongrui** [comment]
I am the same problem, when I use "/chat" to send a wechat message.

**Comment by blueset** [comment]
Please ensure that there are no other process using `tgdata.db` before EFB is started, and ensure that EFB process has the permission to access that file.

**Comment by lyckyercyber** [comment]
same issue here
same trigger as 'I am the same problem, when I use "/chat" to send a wechat message.'
I'm sure 'there are no other process using tgdata.db before EFB is started, and ensure that EFB process has the permission to access that file.'

**Comment by ddqp** [comment]
same issue here,

**Comment by blueset** [comment]
As I cannot reproduce in my environment, I would like to seek help to those who can reproduce this issue stably.

**Comment by blueset** [comment]
This issue was moved to blueset/efb-telegram-master#6
