### ISSUE TITLE
suggest /link function list recent conversation at top

### ISSUE THREAD

**Issue by xufan6** [blueset/ehForwarderBot#7]
I have many groups chat in wechat, if I want to /link into tg group, I need press many next button under /link.
If the /link function can list recent conversation at top, it will more easy to use

**Comment by blueset** [comment]
@xufan6 EFB Telegram Master (ETM) supports filtering chats list (both /link and /chat) with regular expressions. (E.g.: /link John will give give you all chats with the word "John".)

For a detailed usage, please refer to the [documentation](https://ehforwarderbot.readthedocs.io/en/latest/ETM/#chat-chat-head).
