### ISSUE TITLE
Telegram消息转发给错误的微信用户

### ISSUE THREAD

**Issue by gaoyifan** [blueset/ehForwarderBot#70]
感谢您杰出的软件😄 

我在使用过程中遇到一个bug，以下是详情：

【现象】
有两个微信用户A和B，用户A与Telegram群组（称为 `G` ）创建了link，用户B没有创建任何link。

起初，一切正常：A用户从微信发来的消息可以在 `G` 中收到，`G`中发出的消息也会发给微信用户A。

过了一段时间（大约数日），发生奇怪的现象：A用户从微信发来的消息仍然可以在 `G` 中收到，但`G`中发出的消息实际会发给B。且B发来的消息也会显示在`G`中。

【尝试】
1. 重启EFB进程，没有效果。
2. 执行`/unlink_all`，然后重新link，没有效果。
3. 删除EFB数据库。重新运行EFB后，刚开始的几天正常，几天后再次发生同样的故障，并且仍然是A和B用户出现错误。
4. 执行`/chat A`，新建一个A用户的消息头，在Telegram上发给A的消息仍然会转发给B的微信。

【环境】
* EFB version:  1.6.4
* OS inside docker: alpine 3.6
* Docker Image: [gaoyifan/ehforwarderbot](https://hub.docker.com/r/gaoyifan/ehforwarderbot/) [构建脚本](https://github.com/gaoyifan/docker-ehForwarderBot/blob/master/.docker/build)

【日志】
采集过程：
1. 启动EFB
2. 在Telegram中给A发送一条消息，消息内容`ping`（实际发给了B）
3. 保存stdout+stderr，并关闭EFB

日志文件 [efb.log.gz](https://github.com/blueset/ehForwarderBot/files/1185176/efb.log.gz)
注：其中用户A的别名已替换为`__USER_A__`，用户B的别名已替换为`__USER_B__`。

**Comment by gaoyifan** [comment]
发现了一条线索：用户A和用户B的姓名（Name/昵称）是相同的

**Comment by DaZui** [comment]
原文中有提到微信没有稳定的会话识别，所以用昵称来完成会话识别工作。所以昵称相同就串了。使用备注来区分这两个人。

**Comment by gaoyifan** [comment]
@DaZui  备注名的确是不同的

**Comment by blueset** [comment]
如果要将备注名称作为 ID 生成依据的话，请将 `"alias"` 放在 `"uid_order"` 的第一位。
注意：所有已经设置备注的好友，如果备注与当前昵称不同的，将会被视为新的会话。

设置方式请参见 EWS 的 `Experimental flags/"uid_order"` 部分。

**Comment by gaoyifan** [comment]
非常感谢您的回复！
 
针对uid_order的说明还有一些疑问：
请问如果设置`uid_order: ["alias"]`是否会引起讨论组功能出现异常？
如果设置`uid_order: ["NickName", "alias"]`是否会导致所有会话都被视为新的会话？
盼望解答~

**Comment by blueset** [comment]
在你的这个情况的话，`"uid_order"` 的话建议设成 `["alias", "NickName"]`。
* 如果不加 `NickName`, 没有备注的好友、公众号、群组会出问题。
* 如果 NickName 在前面，那么备注只会对没有昵称的群组起作用 (which is rare)。

**Comment by gaoyifan** [comment]
明白了~ 非常感谢~
