### ISSUE TITLE
This group is not linked to any chat. (UC06)

### ISSUE THREAD

**Issue by Domonlee** [blueset/ehForwarderBot#80]
麻烦请问下，我目前的操作步骤是看appinn配置的。在和机器人聊天是没有问题的，当我需要link一个wechat用户到tg的group的时候，发送消息会报错。
> This group is not linked to any chat. (UC06)

尝试着在issue里找到之前的答案，关于在GodFather中设置了privacy->disabled,joinggroups->enable.
发现仍然会提示这样的错误。这个是怎么情况呢。

任何的帮助，我都万分感谢。

**Comment by blueset** [comment]
请尝试重新绑定。

**Comment by lintianzhi** [comment]
遇到同样的问题，在电脑上link会出现这样的问题，然后在手机上可以工作 @blueset

**Comment by yangxun** [comment]
测试了一下，Mac端和手机端的Telegram X无法成功link，手机端Telegram可以成功link

**Comment by Voleking** [comment]
同样的问题，macOS 端无法成功link，手机端 Telegram 可以成功 link

**Comment by blueset** [comment]
这个是 Telegram 客户端对于 `startgroup` 指令的处理问题。  ETM v2 中添加了手动绑定的功能。
