### ISSUE TITLE
[Middleware] 消息转发过滤器

### ISSUE THREAD

**Issue by twotwo** [blueset/ehForwarderBot#85]
#60 
1. 期待消息转发过滤器，v2计划什么时候发布呢？
强烈需要“停止转发微信公众号的消息”的功能。或者只转发制定用户和群的消息。

2. 能加一些注释吗？
看了一下代码，没找到下手的地方。

**Comment by reallyimeric** [comment]
说起来的确，每次收到公众号的转发都很烦

在 2017年9月20日 下午12:18，twotwo <notifications@github.com>写道：

**Comment by blueset** [comment]
1. 大概放假了的时候会重新开始着手吧
2. v2 的时候会尽量补全注释

**Comment by blueset** [comment]
Implemented in v2.

**Comment by zhubeilife** [comment]
请问这个功能在V2版本已经有了吗？
