### ISSUE TITLE
Message is not found in database. Please try with another one. (UC03)

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [blueset/ehForwarderBot#86]
## issue

"Message is not found in database. Please try with another one. (UC03)" occurs when replying to a document message(e.g. someone sent a GIF in group).

## part of the error message:

```
2017-09-25 20:14:34,670: plugins.eh_telegram_master.db [INFO]
    get_msg_log 164884364.1718
2017-09-25 20:14:34,671: peewee [DEBUG]
    ('SELECT "t1"."master_msg_id", "t1"."slave_message_id", "t1"."text", "t1"."slave_origin_uid", "t1"."slave_origin_display_name", "t1"."slave_member_uid", "t1"."slave_member_display_name", "t1"."msg_type", "t1"."sent_to", "t1"."time" FROM "msglog" AS t1 WHERE ("t1"."master_msg_id" = ?) ORDER BY "t1"."time" DESC LIMIT 1', ['164884364.1718'])
```

**Comment by blueset** [comment]
I didn't manage to reproduce in my local environment, are you possible to provide a detailed step of reproduction?

**Comment by jqqqqqqqqqq** [comment]
reply to a sticker or audio in bot session, not linked groups

**Comment by blueset** [comment]
This issue was moved to blueset/efb-telegram-master#7
