### ISSUE TITLE
Supress annoying "System message: UselessMsg"

### ISSUE THREAD

**Issue by FiveYellowMice** [blueset/ehForwarderBot#88]
I frequently receive messages saying "System message: UselessMsg", which is very annoying. Is it more optimal to supress this kind of messages since they are "useless"?

**Comment by blueset** [comment]
I will make a switch about it in a future major update.

**Comment by jack980517** [comment]
This could possibly be merged with #54

**Comment by blueset** [comment]
This issue was moved to blueset/efb-wechat-slave#5
