### ISSUE TITLE
不能提示添加好友的请求？

### ISSUE THREAD

**Issue by wolfsilver** [blueset/ehForwarderBot#92]
不能提示添加好友的请求？
网页版是可用收到请求的

**Comment by blueset** [comment]
这个功能是有做出来的。不知你那边是具体什么症状？

**Comment by wolfsilver** [comment]
收不到请求，只能在手机上看到请求，
[image: Inline image 1]
我这把Useless的类型去掉了，应该不影响吧

**Comment by wolfsilver** [comment]
我这号也已经废了，不能用Web微信了。。

**Comment by blueset** [comment]
This issue was moved to blueset/efb-wechat-slave#4
