### ISSUE TITLE
[feature request] : add proxy setting so that EHM could be set inside China Mainland

### ISSUE THREAD

**Issue by kmahyyg** [blueset/ehForwarderBot#96]
Running OS: Tencent Cloud with backdoor cleaned and located in Guangzhou

I think that we could use VPS inside China Mainland to avoid the ban of Wechat Official. But I also have to consider how to connect to telegram server inside GFW. Now I have several ShadowsocksR server but useless......

Need more help or documentation support.

Thanks for your hard work again.

**Comment by blueset** [comment]
The `python-telegram-bot` library (the Telegram bot API wrap ETM is using) accepts HTTP/HTTPS/Socks proxy provided required dependencies are installed.

More info are available at [#50#316260499](https://github.com/blueset/ehForwarderBot/pull/50#issuecomment-316260499) and [python-telegram-bot/python-telegram-bot#518](https://github.com/python-telegram-bot/python-telegram-bot/pull/518)

**Comment by kmahyyg** [comment]
Maybe you should write this into your doc.

**Comment by kmahyyg** [comment]
Two more questions : 

I just add ``` HTTPS_PROXY = "socks://127.0.0.1/1080" ``` to my bash environment , then it's okay , right?
If I do that , will the traffic of Wechat go through the socks5 proxy ?

**Comment by kmahyyg** [comment]
BTW , When sending a photo to a friend via replying the previous msg in the private chat with the bot , the bot tell me that I didn't choose recipients.

I confirmed that I chose the correct msg to reply for.

**Comment by blueset** [comment]
> Maybe you should write this into your doc.
I will probably include that in version 2.


>Two more questions :
> I just add HTTPS_PROXY = "socks://127.0.0.1:1080" to my bash environment , then it's okay , right?
It should be fine.
> If I do that , will the traffic of Wechat go through the socks5 proxy ?
As per documentation of `itchat`, it did not say that it will, but I haven't tried it myself.

> BTW , When sending a photo to a friend via replying the previous msg in the private chat with the bot , the bot tell me that I didn't choose recipients.
> I confirmed that I chose the correct msg to reply for.

Can you reproduce this bug? If so, please open a new issue about this and post the verbose log and detailed step of:
1. **how you produce the first message?**
2. **how you reply to the first message and produce to the error?**

**Comment by gaoyifan** [comment]
@kmahyyg   I tried `HTTPS_PROXY` env variable.  EFB connect to both wechat and telegram via proxy.

**Comment by kmahyyg** [comment]
Thank you a lot. Could dev help us divide the traffic apart?
