### ISSUE TITLE
QR code is not identified.

### ISSUE THREAD

**Issue by kmahyyg** [blueset/ehForwarderBot#97]
After session expired, It noticed me but doesn't show any login notice.

I use the force logout command to relogin.

Using latest version of ETM , then I restart the python daemon and screenshot the QR code and scan.

The latest version of WeChat told me the QR CODE is not identified. Ask me to download the latest WeChat.

???

I ensure that my WeChat is the latest one and I can login to web WeChat in the normal way.

**Comment by kmahyyg** [comment]
It shows {%% elif device ==1} as error code.

**Comment by kmahyyg** [comment]
Update: Something went wrong caused by Tencent.
Need more discussion.

![photo_2017-11-23_17-51-28](https://user-images.githubusercontent.com/16604643/33170175-5337307c-d082-11e7-99b0-914499ac97b9.jpg)

**Comment by blueset** [comment]
QR code from Web WeChat can only be scanned with your camera. Scanning with screenshot is banned by WeChat due to unknown reason. If you cannot log in Web WeChat in the ordinary way, i.e. open it in browser and scan it with your camera, then your Web WeChat may have been turned off by Tencent.

**Comment by kmahyyg** [comment]
Thanks for your advice. My Web wechat can be logged in in a normal way.

Closed #97 .
