### ISSUE TITLE
[enhancement] useless and error notification

### ISSUE THREAD

**Issue by kmahyyg** [blueset/ehForwarderBot#98]
1.   >> Please immediately turn off this EFB instances.
      >>Another bot instance or webhook detected.

But just the only instance online and one phone.

2.  >> 💬👤 System (weixin):
>> System message: UselessMsg

hide it , plz.

**Comment by blueset** [comment]
Relative enhancements are made in EFB-ETM v2 and EFB-EWS v2.

**Comment by Joney0210** [comment]
get that too.

"Please immediately turn off this EFB instances.
Another bot instance or webhook detected."

one user only.

**Comment by kmahyyg** [comment]
Please don't use it since you received msg.Or your wechat web will be blocked like me.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by blueset** [comment]
@Joney0210  If this is sent to you only once, it is caused by Telegram Bot API's glitch, if it is sent continuously, please check if there is any other session using the bot.

Also, in the glitch case, this has no obvious relationship with EWS or Web WeChat.

**Comment by blueset** [comment]
This issue was moved to blueset/efb-wechat-slave#3
