### ISSUE TITLE
can't recieve voice message

### ISSUE THREAD

**Issue by ddqp** [blueset/ehForwarderBot#99]
Raspberry Pi3

here is the output:

01-12-2017:08:03:44,461 ERROR    [__init__.py:457]
     CouldntEncodeError('Encoding failed. ffmpeg/avlib returned error code: 1\n\nCommand:[\'ffmpeg\', \'-y\', \'-f\', \'wav\', \'-i\', \'/tmp/tmptnmwxl1y\', \'-acodec\', \'libopus\', \'-b:a\', \'65536\', \'-f\', \'ogg\', \'/tmp/tmpnfzpwm40\']\n\nOutput from ffmpeg/avlib:\n\nb"ffmpeg version N-89341-gd13b8f68d7 Copyright (c) 2000-2017 the FFmpeg developers\\n  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1) 20170516\\n  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree\\n  libavutil      56.  4.100 / 56.  4.100\\n  libavcodec     58.  6.102 / 58.  6.102\\n  libavformat    58.  2.103 / 58.  2.103\\n  libavdevice    58.  0.100 / 58.  0.100\\n  libavfilter     7.  5.100 /  7.  5.100\\n  libswscale      5.  0.101 /  5.  0.101\\n  libswresample   3.  0.101 /  3.  0.101\\n  libpostproc    55.  0.100 / 55.  0.100\\nGuessed Channel Layout for Input Stream #0.0 : mono\\nInput #0, wav, from \'/tmp/tmptnmwxl1y\':\\n  Duration: 00:00:00.72, bitrate: 128 kb/s\\n    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 8000 Hz, mono, s16, 128 kb/s\\nUnknown encoder \'libopus\'\\n"',)Traceback (most recent call last):
  File "/home/pi/Downloads/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 406, in process_msg
    bitrate="65536")
  File "/home/pi/.local/lib/python3.5/site-packages/pydub/audio_segment.py", line 671, in export
    raise CouldntEncodeError("Encoding failed. ffmpeg/avlib returned error code: {0}\n\nCommand:{1}\n\nOutput from ffmpeg/avlib:\n\n{2}".format(p.returncode, conversion_command, p_err))
pydub.exceptions.CouldntEncodeError: Encoding failed. ffmpeg/avlib returned error code: 1

Command:['ffmpeg', '-y', '-f', 'wav', '-i', '/tmp/tmptnmwxl1y', '-acodec', 'libopus', '-b:a', '65536', '-f', 'ogg', '/tmp/tmpnfzpwm40']

Output from ffmpeg/avlib:

b"ffmpeg version N-89341-gd13b8f68d7 Copyright (c) 2000-2017 the FFmpeg developers\n  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1) 20170516\n  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree\n  libavutil      56.  4.100 / 56.  4.100\n  libavcodec     58.  6.102 / 58.  6.102\n  libavformat    58.  2.103 / 58.  2.103\n  libavdevice    58.  0.100 / 58.  0.100\n  libavfilter     7.  5.100 /  7.  5.100\n  libswscale      5.  0.101 /  5.  0.101\n  libswresample   3.  0.101 /  3.  0.101\n  libpostproc    55.  0.100 / 55.  0.100\nGuessed Channel Layout for Input Stream #0.0 : mono\nInput #0, wav, from '/tmp/tmptnmwxl1y':\n  Duration: 00:00:00.72, bitrate: 128 kb/s\n    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 8000 Hz, mono, s16, 128 kb/s\nUnknown encoder 'libopus'\n"

**Comment by blueset** [comment]
Please install `libopus` **before** you install `ffmpeg`, and install `ffmpeg` with `libopus` support.

**Comment by ddqp** [comment]
thanks i will try and report here

**Comment by ddqp** [comment]
THANKS, FIXED
